"""empty message

Revision ID: 965fecd84be5
Revises: 502790e8a875
Create Date: 2019-12-21 20:37:42.382817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965fecd84be5'
down_revision = '502790e8a875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accomplishments', sa.Column('isTest', sa.Boolean(), nullable=True))
    op.add_column('activities', sa.Column('isTest', sa.Boolean(), nullable=True))
    op.add_column('challenges', sa.Column('isTest', sa.Boolean(), nullable=True))
    op.add_column('series', sa.Column('isTest', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('isTest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('isTest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isTest')
    op.drop_column('tasks', 'isTest')
    op.drop_column('series', 'isTest')
    op.drop_column('challenges', 'isTest')
    op.drop_column('activities', 'isTest')
    op.drop_column('accomplishments', 'isTest')
    # ### end Alembic commands ###
